name: Test windup e2e
description: Test Windup Addon End-to-End.

runs:
  using: "composite"
  steps:
  - name: test-e2e
    run: make test-e2e
    working-directory: ${{ github.action_path }}/../../..
    shell: bash
