name: Test Windup Addon

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: make fmt
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: make vet
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: make cmd
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make podman-build
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: start-minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
      - name: Build image in minikube
        run: |
          export SHELL=/bin/bash
          export IMG=quay.io/konveyor/tackle2-addon-windup:${{ github.sha }}
          eval $(minikube -p minikube docker-env)
          make docker-build
      - name: install-tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
        with:
          tackle-addon-windup-image: quay.io/konveyor/tackle2-addon-windup:${{ github.sha }}
          tackle-image-pull-policy: IfNotPresent
      - name: Run End-to-End Tests
        run: |
          export HOST=$(minikube ip)/hub
          export NAMESPACE=$(kubectl get tackles.tackle.konveyor.io --all-namespaces --no-headers | awk '{print $1}')
          make test-e2e
